name: incampusdiary
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.0
  intl_phone_field: ^2.0.0
  otp_text_field: ^1.1.0
  flutter_otp: ^0.3.2
  firebase_core: ^1.0.4
  validators: ^3.0.0
  cloud_firestore: ^1.0.6
  google_sign_in: ^5.0.2
  firebase_auth: ^1.1.1
  flutter_svg: ^0.22.0
  google_fonts: ^2.0.0
  provider:
  fluttertoast: ^8.0.6
  flutter_dotenv: ^5.0.2
  percent_indicator: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
     - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Merienda
      fonts:
        - asset: fonts/Merienda-Regular.ttf
          weight: 400
        - asset: fonts/Merienda-Bold.ttf
          weight: 700

    - family: ElMessiri
      fonts:
        - asset: fonts/ElMessiri-Regular.ttf
          weight: 300
        - asset: fonts/ElMessiri-SemiBold.ttf
          weight: 500
        - asset: fonts/ElMessiri-Medium.ttf
          weight: 400
        - asset: fonts/ElMessiri-Bold.ttf
          weight: 700

    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
          weight: 300
        - asset: fonts/Nunito-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/Nunito-Light.ttf
          weight: 200
        - asset: fonts/Nunito-LightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 100
        - asset: fonts/Nunito-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBoldItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/Nunito-Bold.ttf
          weight: 500
        - asset: fonts/Nunito-BoldItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Nunito-Black.ttf
          weight: 700
        - asset: fonts/Nunito-BlackItalic.ttf
          weight: 700
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
